// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Turnero.BaseDatos.Data;

#nullable disable

namespace Turnero.BaseDatos.Migrations
{
    [DbContext(typeof(BDContext))]
    partial class BDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Turnero.BaseDatos.Data.Entidades.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NumeroTelefono" }, "ClienteNumeroTelefono_UQ")
                        .IsUnique();

                    b.ToTable("TablaClientes");

                    b.HasData(
                        new
                        {
                            Id = 1234,
                            Apellido = "Cejas",
                            Email = "",
                            Nombre = "Mariano",
                            NumeroTelefono = "123123"
                        },
                        new
                        {
                            Id = 3456,
                            Apellido = "Aguada",
                            Email = "",
                            Nombre = "Nacho",
                            NumeroTelefono = "35124789"
                        },
                        new
                        {
                            Id = 2345,
                            Apellido = "Marin",
                            Email = "",
                            Nombre = "Tincho",
                            NumeroTelefono = "5234"
                        });
                });

            modelBuilder.Entity("Turnero.BaseDatos.Data.Entidades.Peluquero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImagenPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DNI" }, "PeluqueroDNI_UQ")
                        .IsUnique();

                    b.ToTable("TablaPeluqueros");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Apellido = "Gonzales",
                            DNI = "35.214.872",
                            ImagenPerfil = "",
                            Nombre = "David",
                            Password = "ASD"
                        },
                        new
                        {
                            Id = 23,
                            Apellido = "Del Valle",
                            DNI = "25.214.872",
                            ImagenPerfil = "",
                            Nombre = "Eduardo",
                            Password = "ASD"
                        });
                });

            modelBuilder.Entity("Turnero.BaseDatos.Data.Entidades.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacionTurno")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTurnoReservado")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeluqueroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PeluqueroId");

                    b.HasIndex(new[] { "FechaTurnoReservado", "PeluqueroId" }, "TurnoFechaPeluquero")
                        .IsUnique();

                    b.ToTable("TablaTurnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1234,
                            FechaCreacionTurno = new DateTime(2022, 8, 19, 14, 22, 0, 0, DateTimeKind.Unspecified),
                            FechaTurnoReservado = new DateTime(2022, 10, 22, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            PeluqueroId = 11
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 3456,
                            FechaCreacionTurno = new DateTime(2022, 9, 14, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            FechaTurnoReservado = new DateTime(2022, 9, 23, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            PeluqueroId = 11
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 2345,
                            FechaCreacionTurno = new DateTime(2022, 9, 2, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            FechaTurnoReservado = new DateTime(2022, 9, 12, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            PeluqueroId = 23
                        });
                });

            modelBuilder.Entity("Turnero.BaseDatos.Data.Entidades.Turno", b =>
                {
                    b.HasOne("Turnero.BaseDatos.Data.Entidades.Cliente", "Cliente")
                        .WithMany("ListaTurnos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Turnero.BaseDatos.Data.Entidades.Peluquero", "Peluquero")
                        .WithMany("ListaTurnos")
                        .HasForeignKey("PeluqueroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Peluquero");
                });

            modelBuilder.Entity("Turnero.BaseDatos.Data.Entidades.Cliente", b =>
                {
                    b.Navigation("ListaTurnos");
                });

            modelBuilder.Entity("Turnero.BaseDatos.Data.Entidades.Peluquero", b =>
                {
                    b.Navigation("ListaTurnos");
                });
#pragma warning restore 612, 618
        }
    }
}
